AllCops:
  TargetRubyVersion: 3.3.5
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# TODO: enable
Metrics/ParameterLists:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

# could enable this but i somehow get syntax errors
# in neovim idk maybe i did something wrong
Style/HashSyntax:
  Enabled: false
